language: python

python:
  - pypy3
  - 3.5
  - 3.6

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

jobs:
  include:
    - stage: flake
      python: 3.6
      script:
        - tox -e flake8
    - stage: deploy
      python: 3.6
      script: ignore
      deploy:
        provider: pypi
        user: python-consul-admin
        password:
          secure: "HmLBvgjd5WB8nNBI/KbgvVPKUy1Wsb4TwLL2aEA4IrZHW0/8JHbwwo71zEX+ep+CvqCRTZDMfXtWbckpAJUhjGuqeFqiQGzxwU+SffJsdqy4mVl8NSUJ3WkWItYhPAhnbPYLTOg3QPAEY8KW0RrW1WW3X4wpwEe1+F+o3BDIvvw="
        distributions: "sdist bdist_wheel"
        on:
          tags: true
